remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Occupancy FLEP API
description: Documentation for the Occupancy FLEP API v2